name: PHPStan analysis

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    phpstan:
        runs-on: ubuntu-latest
        container:
            image: php:8.4.6-apache-bullseye
        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  apt-get update
                  apt-get install -y libzip-dev
                  docker-php-ext-install zip pdo_mysql mysqli
                  curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - name: Validate composer.json and composer.lock
              run: |
                  composer validate --strict
            - name: "Restore result cache"
              uses: actions/cache/restore@v4
              with:
                  path: tmp # same as in phpstan.neon
                  key: "phpstan-result-cache-${{ github.run_id }}"
                  restore-keys: |
                      phpstan-result-cache-

            - name: "Run PHPStan"
              run: "vendor/bin/phpstan"

            - name: "Save result cache"
              uses: actions/cache/save@v4
              if: ${{ !cancelled() }}
              with:
                  path: tmp # same as in phpstan.neon
                  key: "phpstan-result-cache-${{ github.run_id }}"
