name: PHPStan analysis

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

permissions:
    contents: read

jobs:
    phpstan:
        runs-on: ubuntu-latest
        container:
            image: php:8.4.6-apache-bullseye
        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  apt-get update
                  apt-get install -y libzip-dev
                  docker-php-ext-install zip pdo_mysql mysqli
                  curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - name: Validate composer.json and composer.lock
              run: |
                  composer validate --strict
            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: buffet-api/vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Run PHPStan
              run: |
                  composer install
                  ./vendor/bin/phpstan analyse --memory-limit 4G -c phpstan.neon --autoload-file vendor/autoload.php --error-format=gitlab src tests >> phpstan-result.json